<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <AvaloniaVersion>11.3.0</AvaloniaVersion>
  </PropertyGroup>
  <ItemGroup>
    <!-- Base packages -->
    <PackageVersion Include="Svg.Controls.Avalonia" Version="11.3.0.1" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="PolySharp" Version="1.15.0" />
    <!-- Avalonia packages -->
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <!-- Markdown packages -->
    <PackageVersion Include="Markdig" Version="0.41.3" />
    <!-- NUnit packages -->
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit.Analyzers" Version="4.5.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="4.6.0" />
    <PackageVersion Include="TextMateSharp" Version="1.0.70" />
    <PackageVersion Include="TextMateSharp.Grammars" Version="1.0.70" />
  </ItemGroup>
</Project>